### ISSUE TITLE
 java.lang.IllegalArgumentException: Invalid format: "Wed Feb 03 14:30:20 AST 2016" is malformed at "AST 2016"

### ISSUE THREAD

**Issue by jagatappv** [dlew/joda-time-android#113]
Hey,

I am using this lib and getting malformed error while parsing it.
 java.lang.IllegalArgumentException: Invalid format: "Wed Feb 03 14:30:20 AST 2016" is malformed at "AST 2016"

Here is the code I am using,
String startTime="Wed Feb 03 14:30:20 AST 2016";
DateTime start = DateTimeFormat.forPattern("EEE MMM DD HH:mm:ss z yyyy").withLocale(Locale.US).parseDateTime(startTime);

Can you provide me the working solution, how can i parse this date using this lib

Thanks

**Comment by Jai-Jiks** [comment]
Getting same error. Anyone solution than please post.

**Comment by dlew** [comment]
The primary problem is that "AST" is a timezone that joda-time doesn't recognize.

In general, short timezones are not supported by joda-time because they are ambiguous. Some of them happen to work (for backwards compatibility) but I doubt they all do.

This is a problem in the base project, not joda-time-android. Please report the issue here: https://github.com/JodaOrg/joda-time
