### ISSUE TITLE
Wrong default timezone on DateTime.now

### ISSUE THREAD

**Issue by Rhedox** [dlew/joda-time-android#116]
DateTime.Now reports the default timezone to be UTC which is not correct.

I'm in Germany so it should be UTC+1 atm.

I suspect this is due to
`            DateTimeZone newDefault = DateTimeZone.forTimeZone(TimeZone.getDefault());
            DateTimeZone.setDefault(newDefault);
`

**Comment by dlew** [comment]
What is the exact timezone you have set on the device?

**Comment by Rhedox** [comment]
It is an emulator set to automatic. http://i.imgur.com/ZW5oieU.png

**Comment by dlew** [comment]
What happens if you output `TimeZone.getDefault()`? I'm not exactly sure what CEST is supposed to correlate to in the tzdata.

Your suspicion is probably wrong, btw. The reason that's needed is for the `DateTimeZone` to work if your timezone changes. Otherwise joda-time doesn't know that the default timezone has changed.

**Comment by murgo** [comment]
This is happening to me also. DateTime.now().getZone() returns UTC, I'm in Finland (so UTC+2). Also DateTimeZone.getDefault() returns UTC. Values are from IntelliJ IDEA debugger debugging real device, Samsung Note 4.

I spent long time trying to figure out, why new DateTime().withHours(0) would change the date. Turns out it interpreted my new DateTime() of 01:00 (+2) as 23:00 (UTC) of the previous day, so the withHours acted little unpredictably.

**Comment by dlew** [comment]
What does `TimeZone.getDefault()` give you? That's really what I'm interested in here...

**Comment by murgo** [comment]
Seems to give Europe/Helsinki as expected.

`libcore.util.ZoneInfo[id="Europe/Helsinki",mRawOffset=7200000,mEarliestRawOffset=7200000,mUseDst=true,mDstSavings=3600000,transitions=117]`

**Comment by dlew** [comment]
I've just tried using `Europe/Helsinki` with the joda-time-android sample on a device and it works fine for me. Hmm... What happens if you try `DateTimeZone.forTimeZone(TimeZone.getDefault())`? I wonder: what is joda-time converting `Europe/Helsinki` into?

Another thought: are you calling `JodaTimeAndroid.init(context);`? If you don't do that, then everything won't work...

**Comment by murgo** [comment]
Doh, the `JodaTimeAndroid.init(context);` makes all the difference. Too bad I didn't notice it 3 hours ago. Maybe the library could throw some kind of exception if it hasn't been initialized?

For me, this issue is fixed now.

**Comment by dlew** [comment]
Alright, problem solved.
