### ISSUE TITLE
Wrong translation for russian text

### ISSUE THREAD

**Issue by deinlandel** [dlew/joda-time-android#133]
Affected file:
https://github.com/dlew/joda-time-android/blob/master/library/src/main/res/values-ru/strings.xml

For quantity="one", number "1" is hardcoded.
This is wrong, because for example number 41 matches quantity="one" in Russian language, so instead of "41 minute ago" we get "1 minute ago" (I used English text just for example)

**Comment by deinlandel** [comment]
Looks like other language also might be affected, depending on their grammar rules. as far as I can see, number "1" is hardcoded for quantity="one"  in many translations.

**Comment by deinlandel** [comment]
[Fixed version of russian translation](https://gist.github.com/deinlandel/fa06cc0571d21958c9594d372e168ee1)

**Comment by dlew** [comment]
Want to submit a PR so I can give proper credit?

**Comment by MenoData** [comment]
This concerns French, too. For example, French zero uses singular, not plural.

And I also see another problem: If someone wants full text then there are often abbreviations only (for example the Russian word for "minutes" is only written as "мин."). Maybe this problem is inherited from Android-DateUtils where they tried to circumvent the fact that many languages (for example most Slavish languages or Arabic) have more than only one plural form.

Libraries with much better i18n-support are ICU4J and my lib Time4A which don't show these symptoms. The whole thing seems to be inherited from Android. Several people have complained about but without success until now, see also https://code.google.com/p/android/issues/detail?id=8287.

**Comment by dlew** [comment]
This part of joda-time-android was just a straight up port of the Android code, so any mistakes there will get transferred here.

**Comment by MenoData** [comment]
I have now done some research. A newer version (see https://github.com/android/platform_frameworks_base/blob/4535e11fb7010f2b104d3f8b3954407b9f330e0f/core/res/res/values-ru/strings.xml) has this content:

```
843     <plurals name="duration_minutes" formatted="false" msgid="643786953939956125"> 
844       <item quantity="one"><xliff:g id="COUNT">%d</xliff:g> минута</item> 
845       <item quantity="few"><xliff:g id="COUNT">%d</xliff:g> минуты</item> 
846       <item quantity="many"><xliff:g id="COUNT">%d</xliff:g> минут</item> 
847       <item quantity="other"><xliff:g id="COUNT">%d</xliff:g> минут</item> 
848     </plurals> 
```

So it seems a solution for your problem is just updating all relevant resources and your adaptation of class `android.text.format.DateUtils` to the newest version.

**Comment by dlew** [comment]
Sounds good to me. I'll have to find some time to run https://github.com/dlew/joda-time-android/blob/master/utils/resource_extractor.py again.

**Comment by dlew** [comment]
I tried running the resource extractor again but ran into some problems. Mainly, in API 23 added more things from ICU4J to internal AOSP, so they can rely on it more than before. That means there are no actual strings in the resources for me to use.

We could either start importing those parts of ICU4J here as well, or we could give up and deprecate support for anything that required resources before (namely just `getRelativeTimeSpanString()`, `getRelativeDateTimeString()` and `formatDuration()`).

**Comment by dlew** [comment]
I think the halfway solution for the next release is going to be to gather the latest translations (for what we can), and otherwise split off that functionality into another lib.

**Comment by dlew** [comment]
Closing because this is too stale and we're probably not going to update the strings.
