### ISSUE TITLE
gettind error on build

### ISSUE THREAD

**Issue by sergey-pokrovskyi** [dlew/joda-time-android#184]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK org/joda/time/format/messages_en.properties
	File1: C:\Users\!!!!!!!!\.gradle\caches\modules-2\files-2.1\joda-time\joda-time\2.9.9\f7b520c458572890807d143670c9b24f4de90897\joda-time-2.9.9.jar
	File2: C:\Users\!!!!!!!!\.gradle\caches\modules-2\files-2.1\joda-time\joda-time\2.9.9\1d2a6ee94f2fcaa2e2b588cbd5a4da1cb1f1b9ff\joda-time-2.9.9-no-tzdb.jar

and this
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/joda/time/base/AbstractDateTime.class

**Comment by sergey-pokrovskyi** [comment]
and this
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/joda/time/base/AbstractDateTime.class

**Comment by sergey-pokrovskyi** [comment]
sorry, i'v found the error:
i use library - https://github.com/anjlab/android-inapp-billing-v3
it updated, and stated to use
`compile 'joda-time:joda-time:2.9.9'`
i cant figure out what to do here =(

**Comment by dlew** [comment]
joda-time-android is incompatible with using the base joda-time library.

You should talk to the library about either using joda-time-android or using `joda-time:joda-time:2.9.9:no-tzdb`. Alternatively, you could forcibly remove the joda-time package from the library. Either way is a good move because of the reasons for not using the default joda-time library: https://github.com/dlew/joda-time-android#why-joda-time

Regardless, this is not a bug with joda-time-android. It's an incompatible dependency setup.
