### ISSUE TITLE
Why is it needed to initialize with JodaTimeAndroid.init(this); ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dlew/joda-time-android#187]
Is it to prevent change of function calls that need to involve Context?
If so, in which cases?

**Comment by dlew** [comment]
It's used to initialize the library, because it needs access to `Context` in order to operate.

If I were to rewrite the library from scratch these days, I'd probably use the `ContentProvider` initialization trick. But I don't want to fix what isn't broken, so it'll stay this way until some compelling reason makes me change it.

**Comment by AndroidDeveloperLB** [comment]
I noticed though that for samples on Joda, it works without initialization of the context.
So, in which cases does it use the Context?

**Comment by dlew** [comment]
Pure Java joda-time does not require `Context` because it can load data from its own JAR. However, this has proven to be a bad practice on Android, thus we load it from resources here. See more on why here: https://github.com/dlew/joda-time-android#why-this-library

**Comment by AndroidDeveloperLB** [comment]
I don't understand. You mean that if I don't initialize it with Context, it is loaded from Jar?
That there is a difference between this:

        DateTime dt = new DateTime();


and this:

        JodaTimeAndroid.init(this);
        DateTime dt = new DateTime();

?

**Comment by dlew** [comment]
When you create a `DateTime` it has to get its timezone data from somewhere. There is a static singleton timezone data loader. For this library, you need to pass it the `Context` to get it started. In pure Java joda-time, you don't, because it (by default) grabs it from the JAR.

This is an issue tracker for bugs related to joda-time-android. This isn't a bug, if you have further questions please take it to StackOverflow or the like.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. So the first snippet uses the JAR ? 
If it's so needed, why not throw an exception? Or require a parameter?

**Comment by GlenVH** [comment]
f
