### ISSUE TITLE
hoursbetween() function returning inconsistent results

### ISSUE THREAD

**Issue by kyletan7** [dlew/joda-time-android#194]
`        LocalDateTime now = LocalDateTime.now();
        LocalDateTime fiveDaysAgo = LocalDateTime.now().minusDays(5);

        System.out.println(Days.daysBetween(fiveDaysAgo, now).getDays());
        System.out.println(Days.daysBetween(fiveDaysAgo, LocalDateTime.now()).getDays());`

First one returns 4, whereas the second one returns the correct result, 5. Why is this? 
This is also happening for the other sister functions (hours, etc)

**Comment by MenoData** [comment]
Your code contains a bug. Generally you should not recalculate the expression `LocalDateTime.now()` multiple times but cache the first calculated now-timestamp.

In your example using the first line to determine the delta, `fiveDaysAgo` is slightly earlier than just 5 * 24 hours ago because you have based it on a later now-date, hence the delta is reduced by one day showing four instead of five days.

**Comment by dlew** [comment]
Sorry for the slow response, been out Thanksgiving weekend.

MenoData is correct. If you wanted consistency in the days between, you should be using `LocalDate`, not `LocalDateTime`. The extra precision that the time component adds messes up the days-between calcluation.
