### ISSUE TITLE
new DateTime() uses UTC instead of current system time zone

### ISSUE THREAD

**Issue by kolczak** [dlew/joda-time-android#20]
I compile this lib with gradle and initialise it in Application onCreate().
I am in time zone UTC+2, and this is what my phone indicates.
When I call new DateTime() I always get time in UTC, what is wrong according to documentation.

**Comment by voronnenok** [comment]
I've just fix the same trouble in our project.
The problem is that we first create our dagger graph and only after that we calling JodaTimeAndroid.init().
While graph creating process we have some logic that implicitly creates new DateTime(millis) and at that point only UTCProvider available for DateTimeZone. DateTimeZone caches UTC timezone as default and after calling JodaTimeAndroid.init() and setting ResourceZoneInfoProvider as default provider not changing default timezone.
