### ISSUE TITLE
More than one file was found with OS independent path 'org/joda/time/format/messages_es.properties'

### ISSUE THREAD

**Issue by ColtonIdle** [dlew/joda-time-android#219]
`More than one file was found with OS independent path 'org/joda/time/format/messages_es.properties'`

I'm not sure if it's from a conflicting dependency, but I have plain old joda time in my android app, and was looking to swap this into place for better memory performance as you mention in the readme, and when doing so I got said error.

**Comment by dlew** [comment]
Did you leave the old joda-time dependency in at the same time? You will need to remove that if you switch to joda-time-android (joda-time-android brings in a special version of joda-time which can conflict with the main artifact).

**Comment by ColtonIdle** [comment]
Sorry. I should have clarified that. I don't have the regular joda time dependency anymore. I'm assuming that I have other libraries, that are maybe bringing it in? I just recently converted to androidx as well so I was thinking maybe there's a known issue there.

**Comment by ColtonIdle** [comment]
It looks as though a module I'm using is depending on joda time. I don't necessarily have the ability to update that module version of joda time (It's a custom time picker). What would you recommend in this scenario @dlew ?

**Comment by dlew** [comment]
You can [force removal of transitive Gradle dependencies](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:excluding_transitive_module_dependencies).

The version of joda-time that joda-time-android uses is completely compatible with normal joda-time. The only difference is that it doesn't package tzdata with it (since joda-time-android packages its own tzdata).

**Comment by ColtonIdle** [comment]
Thanks. I'll look into that.
