### ISSUE TITLE
Joda Time Android versioning not in sync with Joda Time

### ISSUE THREAD

**Issue by wbervoets** [dlew/joda-time-android#232]
Joda time version is at 2.10.3 now, https://www.joda.org/joda-time/changes-report.html#a2.10.3

Joda Time android is at 2.10.2 but seems to include the changes of 2.10.3?

Can the versions be brought in sync again? Then I can use one version property in my build scripts?

Thanks
Wim

**Comment by dlew** [comment]
It's not an issue actually.

First, you can always use a newer transitive dependency and it'll get picked up by gradle. E.g., this works:

```
dependencies {
  implementation 'joda-time:joda-time:2.10.3'
  implementation 'net.danlew:android.joda:2.10.2'
}
```

The only time that doesn't work is when the two dependencies are incompatible, but they are compatible in this case.

In fact, the only difference in joda-time 2.10.3 is that it is udpated for the latest tzdata (2019b). joda-time-android *already* updated to 2019.b in our 2.10.2 release, so it's entirely moot to update to the latest joda-time dependency (which is why it hasn't been done yet).
