### ISSUE TITLE
Migrating from version 2.10.7.2 to 2.10.9 cause the App to crash on launch

### ISSUE THREAD

**Issue by elye** [dlew/joda-time-android#277]
When migrating from

```
    implementation('net.danlew:android.joda:2.10.7.2') {
        transitive = false
    }
```

to

```
    implementation('net.danlew:android.joda:2.10.9') {
        transitive = false
    }
```

The app will crash on launch with message

```
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider"
```

Is there something has changed from 2.10.7.2 till 2.10.9 that need to app to changed as well?

**Comment by dlew** [comment]
joda-time-android now depends on the AndroidX startup library. By disabling transitive dependencies, it disables that library.

Why are transitive dependencies disabled? That would break most libraries...

**Comment by elye** [comment]
Without `transitive = false`, it fails with

```
Duplicate class org.joda.time.Chronology found in modules jetified-joda-time-2.10-no-tzdb.9-no-tzdb (joda-time:joda-time:2.10.9) and jetified-joda-time-2.10.9 (joda-time:joda-time:2.10.9)
```

**Comment by elye** [comment]
Currently we workaround the issue by also adding `implementation "androidx.startup:startup-runtime:1.0.0"` to our app.

**Comment by dlew** [comment]
Ah, the problem is that you should not be including both `joda-time` and `joda-time-android` in your app. That's why you're getting the failures; `joda-time-android` uses a special version of `joda-time` that does NOT include the tzdata (because otherwise you'd be duplicating that data, bloating your APK).

If you get rid of your direct dependency on `joda-time`, and remove `transitive = false`, it should all work.
