### ISSUE TITLE
Froyo Support?

### ISSUE THREAD

**Issue by mazurio** [dlew/joda-time-android#28]
Is there any particular reason why joda-time-android does not support API 8?

**Comment by dlew** [comment]
Extremely low demand. There was another ticket no one said anything about for a long time: https://github.com/dlew/joda-time-android/issues/8

Technically, it's because of `Arrays.copyOf()`, which is present in joda-convert. I'd have to investigate deeper whether or not that converter is actually used in joda-time itself, which would take time, which is more than I want to do. :)

If someone else wants to prove it's not being used it could support 8 again, but... seriously, 8 is a bit low at this point.

**Comment by mazurio** [comment]
That's true, we are currently debating if to drop support for Froyo but there is around 4,000 active users from 2.2 only for us, which is why I ask. Moving from Joda to Joda-Android dropped memory usage quite a lot.

**Comment by mazurio** [comment]
Also it looks like it can be easily moved to System.arraycopy:
http://stackoverflow.com/questions/14723748/most-efficient-way-to-make-a-copy-of-a-large-array-in-java

**Comment by dlew** [comment]
Even if you could replace the code easily, the proper way to do it would be in [joda-convert](https://github.com/JodaOrg/joda-convert), which is a dependency for [joda-time](https://github.com/JodaOrg/joda-time), which is a dependency for this library. So it would take a bit of time. :)

Alternatively you could prove that that form of string conversion isn't used by joda-time itself, since joda-convert is a general utility library.

**Comment by mazurio** [comment]
So if joda-time is using the same library and I had no problems with it on Froyo I guess I am still free to try and just joda-android for API 8?

**Comment by dlew** [comment]
Yeah, that's probably correct.

I suspect joda-time isn't using that method, but I don't want to lower the minSdkVersion unless I have proof that it's alright.
