### ISSUE TITLE
Parsing time zone issue

### ISSUE THREAD

**Issue by sqaaa** [dlew/joda-time-android#285]
Hello! I have an issue with parsing date in iso8601 format with this kind of exception
![image](https://user-images.githubusercontent.com/11176780/114004584-795b1d80-9867-11eb-911a-4dff02d21bc1.png)

I'm using this pattern for parsing
`DateTime.parse(date8601, DateTimeFormat.forPattern(DATE_TIME_8601))`
where `DATE_TIME_8601` is `"yyyy-MM-dd'T'HH:mm:ss.SSSZ"`
and it's working good for the most of cases

Could you give me a hint on how would we overcome this type of parsing issue?

I can't provide you more info about the device or android version, because that is one of our users and we can't reproduce it on our end by changing the time zone to this one.

Thank you in advance and have a nice day!

**Comment by dlew** [comment]
Hey - chances are that you're trying to parse a time which technically doesn't exist due to timezone oddities and implementation quirks.

What you may be doing is simply a limitation of joda-time itself, unfortunately: https://github.com/JodaOrg/joda-time/issues/507#issuecomment-508499247

There's some more info on it illegal instants here: http://joda-time.sourceforge.net/faq.html#illegalinstant

Since this is more of an issue with the base library, joda-time, than with joda-time-android, I'm going to close this out.
