### ISSUE TITLE
Parsing issue with short month format

### ISSUE THREAD

**Issue by bazimogmbh** [dlew/joda-time-android#320]
```
  String pattern = "MMM yyyy";
  DateTimeFormatter dtfOut = DateTimeFormat.forPattern(pattern);
  DateTime dateTime = new DateTime();
```

The expected output would be **Oct 2022**, but it gives **M10 2022** on android 12, with the latest 2.11.2 joda-time-android sdk.

**Comment by dlew** [comment]
`DateTimeFormat` is part of joda-time and `DateTimeFormatter` is part of the Android SDK; neither are part of this library (which just provides Android extensions for joda-time).

I would try reproducing the issue without joda-time-android and see if it still occurs (which I'm betting it does, since it relies almost entirely on non-joda-time-android code); if it does you can reopen the bug.
