### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mandrachek** [dlew/joda-time-android#341]
It would be nice if the joda-time-android version was prefixed with the exact joda-time version.

So that all versions based on say, joda 2.12.1 would be 2.12.1.something.

Currently android-joda is 2.12.6, but the core joda version still appears to be 2.12.1 (the latest I think is 2.12.5).  So if android-joda was 2.12.1.6, that would make it easier to keep joda and android-joda versions in sync (I do this for unit tests), instead of having to check the ChangeLog every release.

**Comment by dlew** [comment]
There is also rarely a reason for tying exact versions of joda-time to joda-time-android, so I don't bother making a new joda-time-android release when joda-time-android is already compatible with the latest joda-time release.

I haven't tested it personally but there's nothing in the [joda-time 2.12.6 release notes](https://github.com/JodaOrg/joda-time/releases/tag/v2.12.6) that indicate we'd need to change any of joda-time-android's code to match. So I am unlikely to update joda-time-android until either a new tzdata comes out (at which point I *should* update our pointer to joda-time's latest), or joda-time releases an incompatible version (which has not happened in many years).

-----

That said, I've made some mistakes this year as well. I should be usying `x.y.z.#` if I ever need to release out-of-sync with joda-time but I've been forgetting to do that, sorry.

The first mistake was that joda-time-android v2.12.5 should've updated to using joda-time 2.12.5. The reason it didn't was negligence, though it doesn't matter because it was a no-op release w.r.t. joda-time-android. Both updates were just for tzdata, and this library explicitly discludes joda-time's tzdata.

The second mistake I made was that the latest release should've been v2.12.5.1, to match the naming convention as desired above.

------

This is all to say: if want the latest joda-time code, you should include newer versions of the dependency in your builds. joda-time-android will happily use it, as far as I know (though let me know if it doesn't)!

And thanks for the reminder about versioning, I've been growing too lax about it of recent.
