### ISSUE TITLE
Unit test error

### ISSUE THREAD

**Issue by appmath** [dlew/joda-time-android#37]
I followed the directions on this page: http://tools.android.com/tech-docs/unit-testing-support

I created a test class, compiled it but I ran into this:
Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: sun.misc.Launcher$AppClassLoader@5bdf59bd

I copied everything to a simple Java project (switched to IntelliJ) and my unit tests ran just fine.

Gradle info
compile 'net.danlew:android.joda:2.7.1'
testCompile 'junit:junit:4.12'

**Comment by dlew** [comment]
This is probably another instance of https://github.com/dlew/joda-time-android/issues/36; moving to there.

**Comment by tigerpenguin** [comment]
@appmath In your unit test, are you initializing JodaTimeAndroid with `JodaTimeAndroid.init(context)`? Depending on how your unit test is set up, it may not be calling the JodaTimeAndroid.init() code in your Application. Initializing it in the beginning of the unit test fixes the resource not found problem, but it does lead to other issue:
```
java.lang.NullPointerException
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at net.danlew.android.joda.ResourceZoneInfoProvider.loadZoneInfoMap(ResourceZoneInfoProvider.java:170)
	at net.danlew.android.joda.ResourceZoneInfoProvider.<init>(ResourceZoneInfoProvider.java:39)
	at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:39)
```

I am using Robolectric 3.0 and passing context from `RuntimeEnvironment.application` as shown in https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide-(Draft)

Any tips @dlew? You don't run into issues when running unit tests?

**Comment by dlew** [comment]
I run Android unit tests (no robolectric) so I haven't run into that in particular. What happens if you run the test without robolectric (as a normal Android test)?

**Comment by tigerpenguin** [comment]
Are you talking about InstrumentationTestCase that connects to the emulator? I suppose it will work. I'm guessing it's something to do with Robolectric not picking up the right resources or something (for my case). I'll update once I find out more. I'd be interested in knowing what @appmath is running though, and whether calling `JodaTimeAndroid.init(context)` will fix the problem for him/her.

**Comment by tigerpenguin** [comment]
At least for me, found out it's an issue with Robolectric. When opening raw resources from library, it always returns null - https://github.com/robolectric/robolectric/issues/1430

Wonder if there's a need to use Robolectric anymore, now that Android has native unit test support on the JVM. I should try it out.

**Comment by appmath** [comment]
Thanks @tigerpenguin for the suggestion but I am only unit testing the model/domain/business rules which have absolutely not dependency on Android which explains how I was able to copy and paste these classes and the unit tests (dependency on non-android Joda-Time) to an IntelliJ temp project and quickly run them without any issues.

**Comment by jamesrgrinter** [comment]
I've been trying to write a simple AndroidTestCase, testing a class that invokes JodaTimeAndroid methods and uses timezones, that will run from the command line (gradlew...) and also from Android Studio's debugger (because I'd like to actually find the bugs).

How should I be initialising JodaTimeAndroid.init(context) in my test class setUp() method? All my attempts at getting a context have failed, including attempting to use InstrumentationTestCase.

Surely it must be possible, without running in the emulator?

**Comment by CDRussell** [comment]
Not sure if this comment will be picked up given this issue is closed, but the linked issues don't seem like the right place for the either.

I'm in the same boat as @appmath in that I have pure model/domain/business rules which have no Android dependency, but *do* live inside the same project as my main android app.

I already have a depdendency on joda-time-android for my app, but ideally would like a way of avoiding the `java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap"` error during pure JUnit tests (not android instrumentation, not robolectric).

Is the only solution to separate these into a separate Java-only module? or is there a way to override the android joda time with normal joda time for testing?

**Comment by legarspol** [comment]
Same problem here. We can't create DateTime object while doing pure unit testing as we don't have any context to initialize JodaTime with...
I'm avoiding the problem by replacing DateTime instances with null for now but stop me from testing if model survive parceling and so on.

**Comment by dlew** [comment]
@legarspol If you're doing a pure unit test, then just include `joda-time` for it instead of `joda-time-android`.

**Comment by victorhurdugaci** [comment]
@dlew probably trivial question but how do you include `joda-time` just for testing?

**Comment by PaulWoitaschek** [comment]
@victorhurdugaci 
```groovy
testCompile 'joda-time:joda-time:2.9.4.2'
```

**Comment by imminent** [comment]
So, `testCompile` doesn't resolve the  crash for me in standard JUnit tests. I've tried something like this even:

```
debugCompile 'net.danlew:android.joda:2.8.1'
releaseCompile 'net.danlew:android.joda:2.8.1'
testCompile 'joda-time:joda-time:2.8.1'
```

In the past I avoided this by only using `UTC` and `DateTimeZone.forOffset()`, but it looks like the `DateTimeFormatter.print`

I avoided the crash by setting `DateTimeZone.setDefault()` to an explicit timezone, such as `UTC`.

**Comment by ymka** [comment]
I've resolved "java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap"" next way:

```java   
@Before
public void prepareBeforeTests() {
    Context context = mock(Context.class);
    Context appContext = mock(Context.class);
    Resources resources = mock(Resources.class);
    when(resources.openRawResource(anyInt())).thenReturn(mock(InputStream.class));
    when(appContext.getResources()).thenReturn(resources);
    when(context.getApplicationContext()).thenReturn(appContext);
    JodaTimeAndroid.init(context);
}
```

Does it resolve your issues?
