### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by danielgomezrico** [dlew/joda-time-android#71]
Using Espresso and JUnit 4 I get:

```
java.lang.NoSuchMethodError: org.joda.time.DateTime.now
```

Have to add manualy `-keepclassmembers class org.joda.time.DateTime.xxxx { public *; }` to my proguard file

**Comment by dlew** [comment]
The problem you're running into is that test proguard doesn't use the test sources when computing what to remove and you don't use `DateTime.now()` in your app. That is, the build process looks like this:

1. Compile all the app source files.
1. Process them with proguard.
1. Create an APK.
1. Compile your test source files.
1. Run tests against APK.

As you can see, proguard runs way before you even get to the test sources.

I suggest creating a proguard file for testing that hooks into the gradle parameter `testProguardFile`, wherein you can be far more permissive of what's included (since it's only run against test files).

**Comment by danielgomezrico** [comment]
but I'm using it inside my api library and was using that auto import for proguard that you just added to this lib, any way to use it for tests automatic too?

**Comment by dlew** [comment]
The proguard being included automatically with the library is only for the essentials. It won't cover your back if some of your code is being removed because your APK isn't referencing it at all.

**Comment by danielgomezrico** [comment]
Makes sense, thanks
