### ISSUE TITLE
Writing a simple AndroidTestCase, need to call JodaTimeAndroid.init()

### ISSUE THREAD

**Issue by jamesrgrinter** [dlew/joda-time-android#75]
I've been trying to write a simple AndroidTestCase, testing a class that invokes JodaTimeAndroid methods and uses timezones, that will run from the command line (gradlew...) and also from Android Studio's debugger (because I'd like to actually find the bugs).

How should I be initialising JodaTimeAndroid.init(context) in my test class setUp() method? All my attempts at getting a context have failed, including attempting to use InstrumentationTestCase.

Surely it must be possible, without running in the emulator?

**Comment by dlew** [comment]
In your tests you could use joda-time instead of joda-time-android, which has no dependency on Android. Alternatively, I've heard of people using Robolectric to run tests without using an emulator.

This issue tracker is specifically for problems with joda-time-android; testing Android-specific libraries without using the emulator is a problem for all Android libraries.
