### ISSUE TITLE
NoClassDefFoundError: net.danlew.android.joda.ResourceZoneInfoProvider on KitKat devices

### ISSUE THREAD

**Issue by lezardos** [dlew/joda-time-android#99]
Hi,

We are getting this error on devices with KitKat and below. On devices with Lollipop or Marshmallow, we have no problem. 

This is what we add in our build.gradle : compile 'net.danlew:android.joda:2.9.0'
JodaTimeAndroid.init(this); is done in Application onCreate.

Any idea why we are getting this error ?

Thx in advance !

![capture d ecran 2015-11-30 a 09 49 30](https://cloud.githubusercontent.com/assets/5501874/11467337/b2cb78ca-9747-11e5-8c93-6a31be21171d.png)

**Comment by dlew** [comment]
I've only ever seen this happen because of a bad build. Try cleaning/rebuilding.

**Comment by lezardos** [comment]
We have already tried that many times.

One precision, this happen on samsung devices (S4 mini and Tab 3).

**Comment by dlew** [comment]
Oh whoops, I misread this initially. ZoneInfoMap != ResourceZoneInfoProvider. Chalk it up to having just woken up. :P

The fact that it works on some devices and not others rules out proguard. But are you using multidex? That might be the culprit, since obviously your `Application` code would be in the primary dex file (but joda-time-android's classes could be in a secondary dex file).

On Lollipop+, multidex would happen naturally; but on KitKat and below you'd have to invoke the legacy multidex BEFORE trying to initialize joda-time.

**Comment by theyann** [comment]
Indeed it worked when using legacy multidex. Thanks for pointing this out Dan.

**Comment by lezardos** [comment]
For those searching how to use legacy multidex,  http://developer.android.com/reference/android/support/multidex/MultiDexApplication.html

**Comment by mismanc** [comment]
I was working in Linux base operating system and JodaTime.init() was working. I have passed to Windows for some reasons. After I checkout project I get this error. I rebuild project. Now it is working. No more thing I do.
